import { FailedPublish, PublishResults, PublishedPackages } from "./publish";
import fs from "fs";
import { markdownTable } from "markdown-table";

export function formatComment({ published }: { published: PublishResults }): string {
  let { tag, publishedPackages, unsuccessfulPublishes } = published;
  let footer = "\n<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions <img alt='Frontside' height='16' src='https://frontside.com/favicon-32x32.png?v=de93ee3512df754fd0cc381d84527025'/></a><em></p>";
  let successfulPublishes = "The following preview packages were published:\n"+tableOfPublishedPackages({ publishedPackages, tag });
  let failedPublishes = "🚨 We were unable to publish these packages:\n"+tableOfFailedPublishes({ unsuccessfulPublishes });

  if (publishedPackages.length >= 1 && unsuccessfulPublishes.length >= 1
  ) {
    return successfulPublishes+failedPublishes+footer;
  } else if (publishedPackages.length >= 1) {
    return successfulPublishes+footer;
  } else if (unsuccessfulPublishes.length >= 1) {
    return failedPublishes+footer;
  } else {
    return "📣 NOTIFICATION\nYou are receiving this message because we did not publish any packages."+footer;
  }
}

function preCodeWrap (child: string) {
  return `<br><pre><code>${child}</code></pre>`;
}

function tableOfPublishedPackages ({
  publishedPackages,
  tag,
}:{
  publishedPackages: PublishedPackages[],
  tag: string,
}) {
  let installCommand = fs.existsSync("yarn.lock") ? "yarn add" : "npm install";
  return markdownTable([
    ["Name", "Version", "Install Command"],
    ...publishedPackages.map(pkg => {
      return [
        preCodeWrap(pkg.packageName),
        preCodeWrap(pkg.version),
        preCodeWrap(`${installCommand} ${pkg.packageName}@${tag}`),
      ];
    }),
  ], { align: [ "c", "c", "" ] });
}

function tableOfFailedPublishes ({
  unsuccessfulPublishes
}:{
  unsuccessfulPublishes: FailedPublish[],
}) {
  return markdownTable([
    ["Name", "Attempted Versions"],
    ...unsuccessfulPublishes.map(pkg => {
      return [
        preCodeWrap(pkg.packageName),
        preCodeWrap(pkg.versions.join(", "))
      ]
    })
  ], { align: [ "c", "" ]})
}
