import { PublishResults, PublishedPackages } from "./publish";
import fs from "fs";
import { markdownTable } from "markdown-table";

export function formatComment({ published }: { published: PublishResults }): string {
  let { tag, publishedPackages } = published;
  let footer = "\n<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions <img alt='Frontside' height='16' src='https://frontside.com/favicon-32x32.png?v=de93ee3512df754fd0cc381d84527025'/></a><em></p>";

  if (publishedPackages.length >= 1) {
    return "The following preview packages were published:\n"
      +tableOfPublishedPackages({ publishedPackages, tag })
      +footer;
  } else {
    return "📣 NOTIFICATION\nYou are receiving this message because we did not publish any packages."
      +footer;
  }
}

function preCodeWrap (child: string) {
  return `<br><pre><code>${child}</code></pre>`;
}

function tableOfPublishedPackages ({
  publishedPackages,
  tag,
}:{
  publishedPackages: PublishedPackages[],
  tag: string,
}) {
  let installCommand = fs.existsSync("yarn.lock") ? "yarn add" : "npm install";
  return markdownTable([
    ["Name", "Version", "Install Command"],
    ...publishedPackages.map(pkg => {
      return [
        preCodeWrap(pkg.packageName),
        preCodeWrap(pkg.version),
        preCodeWrap(`${installCommand} ${pkg.packageName}@${tag}`),
      ];
    }),
  ], { align: [ "c", "c", "" ] });
}
