name: Publish PR Preview
description: Generate Preview Packages

inputs:
  INSTALL_SCRIPT:
    description: "If you need to specify your own install command"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
